### ISSUE TITLE
Need .dll file

### ISSUE THREAD

**Issue by QwertyUser451** [mrt-prodz/NPP-Reverse-Text#3]
Can someone run and add the compiled .dll file? i cannot for the life of me figure out how to and this is exactly what i need to create my minecraft reverse language. i'll try to find an alternative, but it'd be nice as well if someone could do it first.

**Comment by mrt-prodz** [comment]
Hi @sunshimdreemurr , I don't code on windows anymore but I could look up for an old DLL in one of my backups. Not sure if it would still work with the current Notepad++ version as it's pretty old but if you want to give it a try I could send it to you.

**Comment by mrt-prodz** [comment]
@sunshimdreemurr  https://www.mrt-prodz.com/public/data/mrtReverseText.zip
